services:
  db:
    image: mysql:8.4
    container_name: odeo-mysql
    environment:
      MYSQL_DATABASE: odeo
      MYSQL_ROOT_PASSWORD: B13nv3nu3_Lag13r
      MYSQL_ROOT_HOST: '%'          # autorise root depuis le réseau du compose
   # ports:
    #  - "3306:3306"
    volumes:
      - backend_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pB13nv3nu3_Lag13r"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: .
    container_name: odeo-backend
    environment:
      PORT: 9090
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: B13nv3nu3_Lag13r
      DB_DATABASE: odeo
    depends_on:
      db:
        condition: service_healthy      # <-- attend que MySQL soit prêt
    command: ["npm","run","dev"]
    ports:
      - "9090:9090"

volumes:
  backend_mysql_data: